ACCESS_KEY_ID: "AKIA3JLGEL6GT5T3IS5D"
SECRET_ACCESS_KEY: "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"
ROLE_NAME: arn:aws:iam::775992663949:role/lambda-swing-detector

CLIP_LENGTH_SECS: 60
MAX_CLIPS: 5
VIDEO_CUTTER_TARGET_BUCKET: tennis-swings
VIDEO_CUTTER_TARGET_META_FOLDER: clips_meta
VIDEO_CUTTER_TARGET_ROOT_FOLDER: clips
VIDEO_CUTTER_EVENT_BUCKET: tennis-swings
VIDEO_CUTTER_LAYER: arn:aws:lambda:us-east-1:775992663949:layer:moviepy-aubio-layer:1
