service: tennis-swings
frameworkVersion: "2"

custom:
  secrets: ${file(config.dev.yml)}

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  role: ${self:custom.secrets.ROLE_NAME}

package:
  individually: true
  exclude:
    - ./**

functions:
  video-cutter:
    handler: video_cutter_handler.lambda_handler
    package:
      include:
        - video_cutter_handler.py
        - contact_sound_detector.py
    events:
      - s3:
          bucket: ${self:custom.secrets.VIDEO_CUTTER_EVENT_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
          existing: true
    destinations:
      onSuccess: arn:aws:lambda:us-east-1:775992663949:function:tennis-community-api-service-dev-update_upload_clips
    memorySize: 10240
    timeout: 900
    environment:
      ACCESS_KEY_ID: ${self:custom.secrets.ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${self:custom.secrets.SECRET_ACCESS_KEY}
      CLIP_LENGTH_SECS: ${self:custom.secrets.CLIP_LENGTH_SECS}
      MAX_CLIPS: ${self:custom.secrets.MAX_CLIPS}
      TARGET_BUCKET: ${self:custom.secrets.VIDEO_CUTTER_TARGET_BUCKET}
      TARGET_META_FOLDER: ${self:custom.secrets.VIDEO_CUTTER_TARGET_META_FOLDER}
      TARGET_ROOT_FOLDER: ${self:custom.secrets.VIDEO_CUTTER_TARGET_ROOT_FOLDER}
    layers:
      - ${self:custom.secrets.VIDEO_CUTTER_LAYER}
